#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


  data:
    elasticsearch:
      cluster-name:
      cluster-nodes: 39.104.207.251:9300